##
@host = http://localhost:8080

### health 
GET /health HTTP/1.1
Host: {{host}}

### login
POST /auth/login HTTP/1.1
Host: {{host}}

{
    "Email": "Yohans4@gmail.com",
    "Password": "Password@123"
}

### create_user
POST /signup HTTP/1.1
Host: {{host}}

{
    "Name": "Yohans Kasaw",
    "Email": "Yohans8@gmail.com",
    "Password": "Password@123"
}

### db-stat 
GET /api/db-stat HTTP/1.1
Host: {{host}}
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}

### all users
GET /api/user HTTP/1.1
Host: {{host}}
Authorization: Bearer {{login.response.body.access_token}}
