##
@host = http://localhost:8080


### ping 
GET /ping HTTP/1.1
Host: {{host}}

### health 
GET /health HTTP/1.1
Host: {{host}}

### all users
GET /user HTTP/1.1
Host: {{host}}

### login 
POST /login HTTP/1.1
Host: {{host}}

{
    "Email": "Yohans4@gmail.com",
    "Password": "Password@123"
}


### creat user
POST /signup HTTP/1.1
Host: {{host}}

{
    "Name": "Yohans Kasaw",
    "Email": "Yohans6@gmail.com",
    "Password": "Password@123"
}

