##
@host = http://localhost:8080

### ping 
GET /ping HTTP/1.1
Host: {{host}}

### login 
POST /auth/login HTTP/1.1
Host: {{host}}

{
    "Email": "Yohans4@gmail.com",
    "Password": "Password@123"
}

### create_user
POST /signup HTTP/1.1
Host: {{host}}

{
    "Name": "Yohans Kasaw",
    "Email": "Yohans8@gmail.com",
    "Password": "Password@123"
}

### health 
GET /api/health HTTP/1.1
Host: {{host}}
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5IiwiZXhwIjoxNzY4MTQ0NTEwLCJpYXQiOjE3NjgwNTgxMTB9.6xjA8lLygSxrmcKDGY_TuaI6Yy1NhA7bpFyHQxrm4ts

### all users
GET /api/user HTTP/1.1
Host: {{host}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5IiwiZXhwIjoxNzY4MTQ0NTEwLCJpYXQiOjE3NjgwNTgxMTB9.6xjA8lLygSxrmcKDGY_TuaI6Yy1NhA7bpFyHQxrm4ts
