/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedHomeProfileRouteImport } from './routes/_authenticated/home.profile'
import { Route as AuthenticatedHomeMatchesRouteImport } from './routes/_authenticated/home.matches'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeProfileRoute =
  AuthenticatedHomeProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)
const AuthenticatedHomeMatchesRoute =
  AuthenticatedHomeMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRouteWithChildren
  '/home/matches': typeof AuthenticatedHomeMatchesRoute
  '/home/profile': typeof AuthenticatedHomeProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRouteWithChildren
  '/home/matches': typeof AuthenticatedHomeMatchesRoute
  '/home/profile': typeof AuthenticatedHomeProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/home': typeof AuthenticatedHomeRouteWithChildren
  '/_authenticated/home/matches': typeof AuthenticatedHomeMatchesRoute
  '/_authenticated/home/profile': typeof AuthenticatedHomeProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/help'
    | '/home'
    | '/home/matches'
    | '/home/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/help' | '/home' | '/home/matches' | '/home/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_auth/login'
    | '/_authenticated/help'
    | '/_authenticated/home'
    | '/_authenticated/home/matches'
    | '/_authenticated/home/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home/profile': {
      id: '/_authenticated/home/profile'
      path: '/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof AuthenticatedHomeProfileRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/home/matches': {
      id: '/_authenticated/home/matches'
      path: '/matches'
      fullPath: '/home/matches'
      preLoaderRoute: typeof AuthenticatedHomeMatchesRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
  }
}

interface AuthenticatedHomeRouteChildren {
  AuthenticatedHomeMatchesRoute: typeof AuthenticatedHomeMatchesRoute
  AuthenticatedHomeProfileRoute: typeof AuthenticatedHomeProfileRoute
}

const AuthenticatedHomeRouteChildren: AuthenticatedHomeRouteChildren = {
  AuthenticatedHomeMatchesRoute: AuthenticatedHomeMatchesRoute,
  AuthenticatedHomeProfileRoute: AuthenticatedHomeProfileRoute,
}

const AuthenticatedHomeRouteWithChildren =
  AuthenticatedHomeRoute._addFileChildren(AuthenticatedHomeRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
